version: '3'
services:
  stock-adviser:
    build:  # This section enables building the image
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Optionally specify Dockerfile name if different
    image: stock-adviser
    container_name: stock-adviser-container
    ports:
      - "80:5000"
    volumes:
      - image_gallery_volume:/app/static
    restart: always  # Optional: restart the container automatically

volumes:
  image_gallery_volume:
    external: true  # Tell Docker to use an external (pre-existing) volume

